### PR TITLE
[FIX] use defaults when creating note_keys instead of only using null

### LINKED ISSUE #1317: mkdachi2 reference dataset
A user from the townhall mentioned that they wanted to use a custom reference dataset in order to do a mkdachi2 meta analysis. However they were unable to select a custom boolean column (aside from included).

A user should be able to select a custom boolean column that represents which analyses to include as a custom curated reference dataset.

### LINKED ISSUE #1332: cannot use boolean column "false" as selector for reference dataset if it contains "null" for one of the notes
context: a user brought up if they try to select another boolean column (besides included), they cannot choose "false" for the reference dataset.

when creating a new annotation, the default value for every note_key (i.e., included) is null from the backend perspective. "included" is a special case where the frontend sets the value to true for all annotations. But when creating other boolean columns, the default is set to "null" and this causes problems when people try to use those columns for analysis selection using "MKDAChi2" or "ALESubtraction" since the reference dataset is only looking for "false" entries, not "null" entries. So the user has to check/uncheck all the null annotations to set them if they want to use that column to filter analyses.

my proposal is to add a "default" attribute to notekeys so that a default value can be specified upon creation of the note_key.

### PR DESCRIPTION
**Pull request by jdkent**
closes #1332 
closes #1317 

This pull request adds another attribute to note_keys to specify a default value, such as "true" or "false", for boolean columns. this pull request sets true for the column "included" and then sets false to all other boolean columns created after it.

### CODE REVIEW

File: compose/neurosynth-frontend/src/pages/Study/hooks/useSaveStudy.tsx [hunk 1]
```diff
@@ -66,7 +66,7 @@ const useSaveStudy = () => {
 
     const handleUpdateBothInDB = async () => {
         try {
-            const updatedStudy = await updateStudyInDB(annotationId as string);
+            const updatedStudy = await updateStudyInDB();
```
Comment (jdkent) [inline compose/neurosynth-frontend/src/pages/Study/hooks/useSaveStudy.tsx]: eslinter edit

File: compose/neurosynth-frontend/src/pages/Study/store/StudyStore.ts [hunk 2]
```diff
@@ -24,7 +24,7 @@ export type StudyStoreActions = {
     initStudyStore: (studyId?: string) => void;
     clearStudyStore: () => void;
     updateStudy: (fieldName: keyof StudyDetails, value: string | number) => void;
-    updateStudyInDB: (annotationId: string | undefined) => Promise<StudyReturn>;
+    updateStudyInDB: () => Promise<StudyReturn>;
```
Comment (jdkent) [inline compose/neurosynth-frontend/src/pages/Study/store/StudyStore.ts]: eslinter edit

File: compose/neurosynth-frontend/src/pages/Annotations/components/EditAnnotationsHotTable.tsx [hunk 3]
```diff
@@ -273,10 +267,17 @@ const AnnotationsHotTable: React.FC<{ annotationId?: string }> = React.memo((pro
...
+        const defaultValue = getDefaultForNoteKey(trimmedKey, columnType);
 
         setAnnotationsHotState((prev) => {
             const updatedNoteKeys = [
-                { key: trimmedKey, type: getType(row.metadataValue), order: 0 },
+                {
+                    key: trimmedKey,
+                    type: columnType,
+                    order: 0,
+                    ...(defaultValue !== undefined ? { default: defaultValue } : {}),
```
Comment (nicoalee) [inline compose/neurosynth-frontend/src/pages/Annotations/components/EditAnnotationsHotTable.tsx]: unnecessarily complex:
```
              {
                    key: trimmedKey,
                    type: columnType,
                    order: 0,
                    defaultValue,
```
